name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04  # ✅ usa una versión compatible
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Instalar dependencias WebKit y xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev xvfb
      - name: Iniciar xvfb
        run: |
          nohup Xvfb :99 -screen 0 1024x768x16 &
          export DISPLAY=:99
      - name: Instalar dependencias npm
        run: npm ci
      - name: Instalar navegadores Playwright
        run: npx playwright install chromium firefox
      - name: Ejecutar tests Playwright
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
